post http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "stuart91",
  "password": "1234"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN0dWFydDkxIiwiaWQiOiI2OTNjNjkxYWJmNGY3ZDk1MTYzNDI3OTIiLCJpYXQiOjE3NjU1Njc2NTZ9.WlA49RAgelL2zL7GfmPENheyob9cKVvdeh26k35-ONI

{
  "title": "token auth whoo",
  "author": "Faeryn",
  "likes": 1,
  "url": "hhtjhu.eu"
}